apiVersion: v1
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Demo Application</title>
        <link href="styles.css" rel="stylesheet" type="text/css">
      </head>
      <body>
        This is an example KOTS application.
        <p>This is text from a user config value: 'please change this value' </p>
        </br>
        This is a hidden value: 'NMGWv9Tl5GW_vG_Lj3qZG6pC9iUdswTVWVHEVWmD'
      </body>
    </html>
  styles.css: |
    body {
      text-align: center;
      background-color: rgb(224,224,224);
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 100%;
    }
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: mia-s-sept-2
  labels:
    kots.io/app-slug: mia-s-sept-2
    kots.io/backup: velero
  name: nginx-content
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtWVFNFZG9ha2N5Y1d3MllYbFphMGhaZFVkdFIzcFFOamt5T2pKRlUwaEhhR3BITW5Gc05tRjVXV3RJV1hWSGJVZDZVRFk1TWc9PSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtWVFNFZG9ha2N5Y1d3MllYbFphMGhaZFVkdFIzcFFOamt5T2pKRlUwaEhhR3BITW5Gc05tRjVXV3RJV1hWSGJVZDZVRFk1TWc9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9999"
    kots.io/app-slug: mia-s-sept-2
  creationTimestamp: null
  labels:
    kots.io/app-slug: mia-s-sept-2
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: miaawong
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtWVFNFZG9ha2N5Y1d3MllYbFphMGhaZFVkdFIzcFFOamt5T2pKRlUwaEhhR3BITW5Gc05tRjVXV3RJV1hWSGJVZDZVRFk1TWc9PSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtWVFNFZG9ha2N5Y1d3MllYbFphMGhaZFVkdFIzcFFOamt5T2pKRlUwaEhhR3BITW5Gc05tRjVXV3RJV1hWSGJVZDZVRFk1TWc9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9999"
    kots.io/app-slug: mia-s-sept-2
  creationTimestamp: null
  labels:
    kots.io/app-slug: mia-s-sept-2
    kots.io/backup: velero
  name: mia-s-sept-2-registry
  namespace: miaawong
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: mia-s-sept-2
    kots.io/when: "true"
  labels:
    app: nginx
    kots.io/app-slug: mia-s-sept-2
    kots.io/backup: velero
  name: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: mia-s-sept-2
  labels:
    app: nginx
    kots.io/app-slug: mia-s-sept-2
    kots.io/backup: velero
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: nginx-content
        kots.io/app-slug: mia-s-sept-2
      labels:
        app: nginx
        kots.io/app-slug: mia-s-sept-2
        kots.io/backup: velero
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-content
      imagePullSecrets:
      - name: mia-s-sept-2-registry
      volumes:
      - configMap:
          name: nginx-content
        name: nginx-content
